import { NextResponse } from "next/server";

export async function POST(req: Request) {
  const formData = await req.formData();
  const file = formData.get("file") as File | null;

  if (!file) {
    return NextResponse.json({ success: false, error: "No file uploaded" }, { status: 400 });
  }

  return NextResponse.json({
    success: true,
    documentId: "demo-upload",
    title: file.name,
    summary:
      "Demo summary generated by the frontend placeholder API. The backend can replace this route with parsing, storage, AI summarization, and indexing.",
  });
}
